[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vixlate"
version = "0.1.0"
requires-python = ">=3.10"

[tool.black]
line-length = 100

[tool.setuptools.packages.find]
where = ["src"]